#!/usr/bin/env bash
# Install dependencies for the dev Home Assistant instance.
set -e
cd "$(dirname "$0")/.."
python3 -m pip install --upgrade pip
python3 -m pip install --requirement requirements.txt
